# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc9f4bbb1b8ed302e927abbb33002bf84f582fc68c5d94d5137190d8b0245bf9c702407e987d6c2c01991a9a520b40e7cfa264d3a61177debafd3082c894cff7

test:
  secret_key_base: 695c03d78459c352d39c20f86a5a20f8c437397f649e1c66c2281e71b50a442d27176a0f8a64d4e59f4d6d96c227a90bf4267b4accbf4335a8a0a840e16a1a66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
